ENV ?= local-demo
ENTERPRISE_SLUG ?= demo-enterprise

.PHONY: init up down status logs seed-demo smoke backup config test-infra

# Copy backend/.env.example to backend/.env on first checkout.
# Operators are expected to fill in CHANGE_ME values before bringing the
# stack up; secrets are NEVER generated by this Makefile or its scripts.
init:
	@test -f backend/.env || cp backend/.env.example backend/.env
	@echo "review backend/.env and fill in CHANGE_ME values"

up:
	./scripts/start.sh $(ENV)

down:
	./scripts/stop.sh $(ENV)

status:
	./scripts/status.sh $(ENV)

logs:
	./scripts/logs.sh $(ENV)

seed-demo:
	./scripts/seed-demo.sh local-demo $(ENTERPRISE_SLUG) "SEED local-demo/$(ENTERPRISE_SLUG)"

smoke:
	./scripts/smoke-test.sh $(ENV)

backup:
	./scripts/backup.sh $(ENV)

config:
	./scripts/compose.sh $(ENV) config --quiet

test-infra:
	./scripts/test-infra.sh
