ENV ?= local-demo
ENTERPRISE_SLUG ?= demo-enterprise

.PHONY: init up down status logs seed-demo create-admin migrate backup restore verify-backup smoke config test-infra alembic-head

# Copy backend/.env.example to backend/.env on first checkout.
# Operators are expected to fill in CHANGE_ME values before bringing the
# stack up; secrets are NEVER generated by this Makefile or its scripts.
init:
	@test -f backend/.env || cp backend/.env.example backend/.env
	@echo "review backend/.env and fill in CHANGE_ME values"

up:
	./scripts/start.sh $(ENV)

down:
	./scripts/stop.sh $(ENV)

status:
	./scripts/status.sh $(ENV)

logs:
	./scripts/logs.sh $(ENV)

migrate:
	cd backend && uv run python scripts/migrate.py --environment $(ENV)

seed-demo:
	cd backend && uv run python scripts/seed_demo.py --environment local-demo \
		--enterprise-slug $(ENTERPRISE_SLUG) --yes

create-admin:
	@echo "Pipe the password into stdin; e.g."
	@echo "  echo 'YourStrongP@ssw0rd' | make create-admin \\"
	@echo "    ADMIN_EMAIL=admin@example.com ADMIN_NAME='Admin User' \\"
	@echo "    ENT_NAME='Acme Inc' ENT_SLUG=acme"
	cd backend && echo "$$ADMIN_PASSWORD" | uv run python scripts/create_admin.py \
		--email $(ADMIN_EMAIL) \
		--display-name "$(ADMIN_NAME)" \
		--enterprise-name "$(ENT_NAME)" \
		--enterprise-slug $(ENT_SLUG)

alembic-head:
	cd backend && uv run python scripts/resolve_alembic_head.py

backup:
	cd backend && uv run python scripts/backup.py --environment $(ENV) --label $(or $(LABEL),manual)

restore:
	cd backend && uv run python scripts/restore.py --environment $(ENV) --backup-dir $(BACKUP_DIR) --yes

verify-backup:
	cd backend && uv run python scripts/verify_backup.py --environment $(ENV) --backup-dir $(BACKUP_DIR)

smoke:
	./scripts/smoke-test.sh $(ENV)

config:
	./scripts/compose.sh $(ENV) config --quiet

test-infra:
	./scripts/test-infra.sh
