"""phase2 intelligence data and file foundation

Revision ID: e6a7c2d941b0
Revises: c5d91f4a8b72
Create Date: 2026-07-27 16:34:50.344996
"""

from typing import Sequence, Union

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e6a7c2d941b0"
down_revision: Union[str, None] = "c5d91f4a8b72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "data_sources",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "configuration_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("secret_reference_key", sa.String(length=200), nullable=True),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_status", sa.String(length=32), nullable=True),
        sa.Column("last_test_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_data_sources_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("enterprise_id", "key", name="uq_data_source_enterprise_key"),
    )
    op.create_index(
        "ix_data_source_enterprise_enabled",
        "data_sources",
        ["enterprise_id", "is_enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_sources_enterprise_id"), "data_sources", ["enterprise_id"], unique=False
    )
    op.create_table(
        "daily_snapshot",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("source_data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column(
            "metrics_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "anomalies_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_daily_snapshot_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_daily_snapshot_organization_unit_id_organization_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_snapshot")),
        sa.UniqueConstraint(
            "enterprise_id",
            "organization_unit_id",
            "snapshot_date",
            name="uq_daily_snapshot_scope_date",
        ),
    )
    op.create_index(
        "ix_daily_snapshot_enterprise_date",
        "daily_snapshot",
        ["enterprise_id", "snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_snapshot_enterprise_id"), "daily_snapshot", ["enterprise_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_snapshot_organization_unit_id"),
        "daily_snapshot",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_table(
        "dim_person",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.String(length=160), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role_title", sa.String(length=160), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("source_system", sa.String(length=80), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_dim_person_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_dim_person_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_dim_person_organization_unit_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dim_person")),
        sa.UniqueConstraint(
            "enterprise_id", "data_source_id", "source_record_id", name="uq_dim_person_source"
        ),
    )
    op.create_index(
        op.f("ix_dim_person_enterprise_id"), "dim_person", ["enterprise_id"], unique=False
    )
    op.create_index(
        op.f("ix_dim_person_organization_unit_id"),
        "dim_person",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_tasks",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("cron_expression", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_enqueued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "configuration_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_scheduled_tasks_data_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_scheduled_tasks_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_tasks")),
        sa.UniqueConstraint("enterprise_id", "key", name="uq_scheduled_task_enterprise_key"),
    )
    op.create_index(
        "ix_scheduled_task_due", "scheduled_tasks", ["is_enabled", "next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_tasks_data_source_id"),
        "scheduled_tasks",
        ["data_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_enterprise_id"), "scheduled_tasks", ["enterprise_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_tasks_next_run_at"), "scheduled_tasks", ["next_run_at"], unique=False
    )
    op.create_table(
        "source_checkpoints",
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=40), nullable=False),
        sa.Column("cursor_value", sa.String(length=500), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_batch_id", sa.String(length=160), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_source_checkpoints_data_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_checkpoints")),
        sa.UniqueConstraint("data_source_id", "domain", name="uq_source_checkpoint_domain"),
    )
    op.create_index(
        op.f("ix_source_checkpoints_data_source_id"),
        "source_checkpoints",
        ["data_source_id"],
        unique=False,
    )
    op.create_table(
        "data_sync_runs",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("source_schema_version", sa.String(length=32), nullable=True),
        sa.Column("source_batch_id", sa.String(length=160), nullable=True),
        sa.Column("source_data_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_read", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.Column(
            "domain_results_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_data_sync_runs_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_data_sync_runs_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_data_sync_runs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sync_runs")),
    )
    op.create_index(
        "ix_data_sync_enterprise_started",
        "data_sync_runs",
        ["enterprise_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_sync_runs_data_source_id"), "data_sync_runs", ["data_source_id"], unique=False
    )
    op.create_index(
        op.f("ix_data_sync_runs_enterprise_id"), "data_sync_runs", ["enterprise_id"], unique=False
    )
    op.create_index(op.f("ix_data_sync_runs_job_id"), "data_sync_runs", ["job_id"], unique=False)
    op.create_index(
        "ix_data_sync_source_status", "data_sync_runs", ["data_source_id", "status"], unique=False
    )
    op.create_table(
        "dim_customer",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=True),
        sa.Column("owner_person_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.String(length=160), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("source_system", sa.String(length=80), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_dim_customer_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_dim_customer_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_dim_customer_organization_unit_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_person_id"],
            ["dim_person.id"],
            name=op.f("fk_dim_customer_owner_person_id_dim_person"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dim_customer")),
        sa.UniqueConstraint(
            "enterprise_id", "data_source_id", "source_record_id", name="uq_dim_customer_source"
        ),
    )
    op.create_index(
        op.f("ix_dim_customer_enterprise_id"), "dim_customer", ["enterprise_id"], unique=False
    )
    op.create_index(
        op.f("ix_dim_customer_organization_unit_id"),
        "dim_customer",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_table(
        "file_extractions",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("parser_name", sa.String(length=80), nullable=True),
        sa.Column("parser_version", sa.String(length=40), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_file_extractions_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_extractions")),
        sa.UniqueConstraint("file_id", name="uq_file_extraction_file"),
    )
    op.create_index(
        "ix_file_extraction_status", "file_extractions", ["status", "updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_file_extractions_file_id"), "file_extractions", ["file_id"], unique=False
    )
    op.create_table(
        "schedule_runs",
        sa.Column("scheduled_task_id", sa.Uuid(), nullable=False),
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("window_key", sa.String(length=160), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enqueued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_schedule_runs_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_schedule_runs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_task_id"],
            ["scheduled_tasks.id"],
            name=op.f("fk_schedule_runs_scheduled_task_id_scheduled_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_runs")),
        sa.UniqueConstraint("scheduled_task_id", "window_key", name="uq_schedule_run_window"),
    )
    op.create_index(
        "ix_schedule_run_status", "schedule_runs", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_runs_enterprise_id"), "schedule_runs", ["enterprise_id"], unique=False
    )
    op.create_index(op.f("ix_schedule_runs_job_id"), "schedule_runs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_schedule_runs_scheduled_task_id"),
        "schedule_runs",
        ["scheduled_task_id"],
        unique=False,
    )
    op.create_table(
        "clarifications",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "options_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("selected_value", sa.String(length=500), nullable=True),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_clarifications_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_clarifications_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_clarifications_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clarifications")),
    )
    op.create_index(
        "ix_clarification_conversation_status",
        "clarifications",
        ["conversation_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clarifications_conversation_id"),
        "clarifications",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clarifications_message_id"), "clarifications", ["message_id"], unique=False
    )
    op.create_table(
        "data_domain_status",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active_sync_run_id", sa.Uuid(), nullable=True),
        sa.Column("previous_sync_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_data_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_display_name", sa.String(length=200), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_sync_run_id"],
            ["data_sync_runs.id"],
            name=op.f("fk_data_domain_status_active_sync_run_id_data_sync_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_data_domain_status_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_data_domain_status_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["previous_sync_run_id"],
            ["data_sync_runs.id"],
            name=op.f("fk_data_domain_status_previous_sync_run_id_data_sync_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_domain_status")),
        sa.UniqueConstraint("enterprise_id", "domain", name="uq_data_domain_enterprise"),
    )
    op.create_index(
        op.f("ix_data_domain_status_data_source_id"),
        "data_domain_status",
        ["data_source_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_domain_status_enterprise",
        "data_domain_status",
        ["enterprise_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_domain_status_enterprise_id"),
        "data_domain_status",
        ["enterprise_id"],
        unique=False,
    )
    op.create_table(
        "fact_delivery",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("manager_person_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.String(length=160), nullable=False),
        sa.Column("opportunity_source_record_id", sa.String(length=160), nullable=False),
        sa.Column("project_code", sa.String(length=120), nullable=False),
        sa.Column("project_name", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("risk_level", sa.String(length=40), nullable=False),
        sa.Column("completion_percent", sa.Integer(), nullable=False),
        sa.Column("contract_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("gross_margin_rate", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("planned_start_date", sa.Date(), nullable=False),
        sa.Column("planned_end_date", sa.Date(), nullable=False),
        sa.Column("actual_end_date", sa.Date(), nullable=True),
        sa.Column("current_milestone", sa.String(length=200), nullable=True),
        sa.Column("delay_days", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=80), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["dim_customer.id"],
            name=op.f("fk_fact_delivery_customer_id_dim_customer"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_fact_delivery_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_fact_delivery_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["manager_person_id"],
            ["dim_person.id"],
            name=op.f("fk_fact_delivery_manager_person_id_dim_person"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_fact_delivery_organization_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["data_sync_runs.id"],
            name=op.f("fk_fact_delivery_sync_run_id_data_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_delivery")),
        sa.UniqueConstraint("sync_run_id", "source_record_id", name="uq_fact_delivery_run_source"),
    )
    op.create_index(
        op.f("ix_fact_delivery_enterprise_id"), "fact_delivery", ["enterprise_id"], unique=False
    )
    op.create_index(
        op.f("ix_fact_delivery_organization_unit_id"),
        "fact_delivery",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_index(
        "ix_fact_delivery_risk_status", "fact_delivery", ["risk_level", "status"], unique=False
    )
    op.create_index(
        "ix_fact_delivery_scope_current",
        "fact_delivery",
        ["enterprise_id", "organization_unit_id", "is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_delivery_sync_run_id"), "fact_delivery", ["sync_run_id"], unique=False
    )
    op.create_table(
        "fact_finance_collection",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.String(length=160), nullable=False),
        sa.Column("project_source_record_id", sa.String(length=160), nullable=False),
        sa.Column("invoice_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("receivable_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("collected_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("outstanding_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("planned_collection_date", sa.Date(), nullable=False),
        sa.Column("actual_collection_date", sa.Date(), nullable=True),
        sa.Column("overdue_days", sa.Integer(), nullable=False),
        sa.Column("aging_bucket", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("source_system", sa.String(length=80), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["dim_customer.id"],
            name=op.f("fk_fact_finance_collection_customer_id_dim_customer"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_fact_finance_collection_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_fact_finance_collection_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_fact_finance_collection_organization_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["data_sync_runs.id"],
            name=op.f("fk_fact_finance_collection_sync_run_id_data_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_finance_collection")),
        sa.UniqueConstraint(
            "sync_run_id", "source_record_id", name="uq_fact_collection_run_source"
        ),
    )
    op.create_index(
        "ix_fact_collection_due_status",
        "fact_finance_collection",
        ["planned_collection_date", "status"],
        unique=False,
    )
    op.create_index(
        "ix_fact_collection_scope_current",
        "fact_finance_collection",
        ["enterprise_id", "organization_unit_id", "is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_finance_collection_enterprise_id"),
        "fact_finance_collection",
        ["enterprise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_finance_collection_organization_unit_id"),
        "fact_finance_collection",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_finance_collection_sync_run_id"),
        "fact_finance_collection",
        ["sync_run_id"],
        unique=False,
    )
    op.create_table(
        "fact_opportunity",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("owner_person_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.String(length=160), nullable=False),
        sa.Column("opportunity_code", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("expected_gross_profit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("expected_close_date", sa.Date(), nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("source_system", sa.String(length=80), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["dim_customer.id"],
            name=op.f("fk_fact_opportunity_customer_id_dim_customer"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_fact_opportunity_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_fact_opportunity_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_fact_opportunity_organization_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_person_id"],
            ["dim_person.id"],
            name=op.f("fk_fact_opportunity_owner_person_id_dim_person"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["data_sync_runs.id"],
            name=op.f("fk_fact_opportunity_sync_run_id_data_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_opportunity")),
        sa.UniqueConstraint(
            "sync_run_id", "source_record_id", name="uq_fact_opportunity_run_source"
        ),
    )
    op.create_index(
        op.f("ix_fact_opportunity_enterprise_id"),
        "fact_opportunity",
        ["enterprise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_opportunity_organization_unit_id"),
        "fact_opportunity",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_index(
        "ix_fact_opportunity_scope_current",
        "fact_opportunity",
        ["enterprise_id", "organization_unit_id", "is_current"],
        unique=False,
    )
    op.create_index(
        "ix_fact_opportunity_stage_close",
        "fact_opportunity",
        ["stage", "expected_close_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_opportunity_sync_run_id"), "fact_opportunity", ["sync_run_id"], unique=False
    )
    op.create_table(
        "fact_target",
        sa.Column("enterprise_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("organization_unit_id", sa.Uuid(), nullable=False),
        sa.Column("source_record_id", sa.String(length=160), nullable=False),
        sa.Column("metric_code", sa.String(length=80), nullable=False),
        sa.Column("metric_name", sa.String(length=160), nullable=False),
        sa.Column("period_type", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("source_system", sa.String(length=80), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_fact_target_data_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_id"],
            ["enterprises.id"],
            name=op.f("fk_fact_target_enterprise_id_enterprises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_fact_target_organization_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["data_sync_runs.id"],
            name=op.f("fk_fact_target_sync_run_id_data_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_target")),
        sa.UniqueConstraint("sync_run_id", "source_record_id", name="uq_fact_target_run_source"),
    )
    op.create_index(
        op.f("ix_fact_target_enterprise_id"), "fact_target", ["enterprise_id"], unique=False
    )
    op.create_index(
        "ix_fact_target_metric_period",
        "fact_target",
        ["metric_code", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_target_organization_unit_id"),
        "fact_target",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_index(
        "ix_fact_target_scope_current",
        "fact_target",
        ["enterprise_id", "organization_unit_id", "is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_target_sync_run_id"), "fact_target", ["sync_run_id"], unique=False
    )
    op.create_table(
        "file_chunks",
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "locator_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["file_extractions.id"],
            name=op.f("fk_file_chunks_extraction_id_file_extractions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_chunks_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_chunks")),
        sa.UniqueConstraint("extraction_id", "chunk_index", name="uq_file_chunk_index"),
    )
    op.create_index(
        "ix_file_chunk_embedding_hnsw",
        "file_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_file_chunk_file", "file_chunks", ["file_id", "chunk_index"], unique=False)
    op.create_index(
        op.f("ix_file_chunks_extraction_id"), "file_chunks", ["extraction_id"], unique=False
    )
    op.create_index(op.f("ix_file_chunks_file_id"), "file_chunks", ["file_id"], unique=False)
    op.create_table(
        "message_evidence",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_key", sa.String(length=80), nullable=False),
        sa.Column("domain", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("metric_code", sa.String(length=100), nullable=True),
        sa.Column("metric_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("metric_unit", sa.String(length=40), nullable=True),
        sa.Column(
            "value_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_display_name", sa.String(length=200), nullable=False),
        sa.Column("source_data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=True),
        sa.Column(
            "scope_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "query_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "row_references_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_evidence_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_evidence")),
        sa.UniqueConstraint("message_id", "evidence_key", name="uq_message_evidence_key"),
    )
    op.create_index(
        "ix_message_evidence_message",
        "message_evidence",
        ["message_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_evidence_message_id"), "message_evidence", ["message_id"], unique=False
    )
    op.create_table(
        "message_routes",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("route", sa.String(length=40), nullable=False),
        sa.Column("profile", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("rewritten_query", sa.Text(), nullable=False),
        sa.Column("scope_status", sa.String(length=40), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_message_routes_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_routes_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_routes")),
        sa.UniqueConstraint("message_id", name="uq_message_route_message"),
    )
    op.create_index(
        op.f("ix_message_routes_conversation_id"),
        "message_routes",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_routes_message_id"), "message_routes", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_routes_message_id"), table_name="message_routes")
    op.drop_index(op.f("ix_message_routes_conversation_id"), table_name="message_routes")
    op.drop_table("message_routes")
    op.drop_index(op.f("ix_message_evidence_message_id"), table_name="message_evidence")
    op.drop_index("ix_message_evidence_message", table_name="message_evidence")
    op.drop_table("message_evidence")
    op.drop_index(op.f("ix_file_chunks_file_id"), table_name="file_chunks")
    op.drop_index(op.f("ix_file_chunks_extraction_id"), table_name="file_chunks")
    op.drop_index("ix_file_chunk_file", table_name="file_chunks")
    op.drop_index(
        "ix_file_chunk_embedding_hnsw",
        table_name="file_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("file_chunks")
    op.drop_index(op.f("ix_fact_target_sync_run_id"), table_name="fact_target")
    op.drop_index("ix_fact_target_scope_current", table_name="fact_target")
    op.drop_index(op.f("ix_fact_target_organization_unit_id"), table_name="fact_target")
    op.drop_index("ix_fact_target_metric_period", table_name="fact_target")
    op.drop_index(op.f("ix_fact_target_enterprise_id"), table_name="fact_target")
    op.drop_table("fact_target")
    op.drop_index(op.f("ix_fact_opportunity_sync_run_id"), table_name="fact_opportunity")
    op.drop_index("ix_fact_opportunity_stage_close", table_name="fact_opportunity")
    op.drop_index("ix_fact_opportunity_scope_current", table_name="fact_opportunity")
    op.drop_index(op.f("ix_fact_opportunity_organization_unit_id"), table_name="fact_opportunity")
    op.drop_index(op.f("ix_fact_opportunity_enterprise_id"), table_name="fact_opportunity")
    op.drop_table("fact_opportunity")
    op.drop_index(
        op.f("ix_fact_finance_collection_sync_run_id"), table_name="fact_finance_collection"
    )
    op.drop_index(
        op.f("ix_fact_finance_collection_organization_unit_id"),
        table_name="fact_finance_collection",
    )
    op.drop_index(
        op.f("ix_fact_finance_collection_enterprise_id"), table_name="fact_finance_collection"
    )
    op.drop_index("ix_fact_collection_scope_current", table_name="fact_finance_collection")
    op.drop_index("ix_fact_collection_due_status", table_name="fact_finance_collection")
    op.drop_table("fact_finance_collection")
    op.drop_index(op.f("ix_fact_delivery_sync_run_id"), table_name="fact_delivery")
    op.drop_index("ix_fact_delivery_scope_current", table_name="fact_delivery")
    op.drop_index("ix_fact_delivery_risk_status", table_name="fact_delivery")
    op.drop_index(op.f("ix_fact_delivery_organization_unit_id"), table_name="fact_delivery")
    op.drop_index(op.f("ix_fact_delivery_enterprise_id"), table_name="fact_delivery")
    op.drop_table("fact_delivery")
    op.drop_index(op.f("ix_data_domain_status_enterprise_id"), table_name="data_domain_status")
    op.drop_index("ix_data_domain_status_enterprise", table_name="data_domain_status")
    op.drop_index(op.f("ix_data_domain_status_data_source_id"), table_name="data_domain_status")
    op.drop_table("data_domain_status")
    op.drop_index(op.f("ix_clarifications_message_id"), table_name="clarifications")
    op.drop_index(op.f("ix_clarifications_conversation_id"), table_name="clarifications")
    op.drop_index("ix_clarification_conversation_status", table_name="clarifications")
    op.drop_table("clarifications")
    op.drop_index(op.f("ix_schedule_runs_scheduled_task_id"), table_name="schedule_runs")
    op.drop_index(op.f("ix_schedule_runs_job_id"), table_name="schedule_runs")
    op.drop_index(op.f("ix_schedule_runs_enterprise_id"), table_name="schedule_runs")
    op.drop_index("ix_schedule_run_status", table_name="schedule_runs")
    op.drop_table("schedule_runs")
    op.drop_index(op.f("ix_file_extractions_file_id"), table_name="file_extractions")
    op.drop_index("ix_file_extraction_status", table_name="file_extractions")
    op.drop_table("file_extractions")
    op.drop_index(op.f("ix_dim_customer_organization_unit_id"), table_name="dim_customer")
    op.drop_index(op.f("ix_dim_customer_enterprise_id"), table_name="dim_customer")
    op.drop_table("dim_customer")
    op.drop_index("ix_data_sync_source_status", table_name="data_sync_runs")
    op.drop_index(op.f("ix_data_sync_runs_job_id"), table_name="data_sync_runs")
    op.drop_index(op.f("ix_data_sync_runs_enterprise_id"), table_name="data_sync_runs")
    op.drop_index(op.f("ix_data_sync_runs_data_source_id"), table_name="data_sync_runs")
    op.drop_index("ix_data_sync_enterprise_started", table_name="data_sync_runs")
    op.drop_table("data_sync_runs")
    op.drop_index(op.f("ix_source_checkpoints_data_source_id"), table_name="source_checkpoints")
    op.drop_table("source_checkpoints")
    op.drop_index(op.f("ix_scheduled_tasks_next_run_at"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_enterprise_id"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_data_source_id"), table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_task_due", table_name="scheduled_tasks")
    op.drop_table("scheduled_tasks")
    op.drop_index(op.f("ix_dim_person_organization_unit_id"), table_name="dim_person")
    op.drop_index(op.f("ix_dim_person_enterprise_id"), table_name="dim_person")
    op.drop_table("dim_person")
    op.drop_index(op.f("ix_daily_snapshot_organization_unit_id"), table_name="daily_snapshot")
    op.drop_index(op.f("ix_daily_snapshot_enterprise_id"), table_name="daily_snapshot")
    op.drop_index("ix_daily_snapshot_enterprise_date", table_name="daily_snapshot")
    op.drop_table("daily_snapshot")
    op.drop_index(op.f("ix_data_sources_enterprise_id"), table_name="data_sources")
    op.drop_index("ix_data_source_enterprise_enabled", table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
